### ISSUE TITLE
Your comparison table should be honest

### ISSUE THREAD

**Issue by teneko** [sethmachine/yatapi#8]
Hi, I am currently working on a compiler ([SCUMSLang](https://github.com/SCUMSLang/SCUMSLang)) on my own and have tried to get the idea behind your comparison table. You are completely right, that these "features" are unique to YOUR project and therefore green checked, but you should be honest, that you're taking off completely the advantages of exactly these tools you named in your comparison table.

Here are some thoughts:

- Language

Instead looking wheather the others are offering to write triggers in python you should say which language interface they offer. (e.g. YATAPI -> Python, LangUMS -> LangUMS and so on)

- Active Project => Latest Release/Contribution

Instead to say if active or not, I would look for latest commit date or latest release date and let the user decide himself.

- Install with pip => Package Manager

Instead to specify concretely pip I would rather categorize it by package manager. (e.g. YATAPI -> pip, LangUMS -> none)

- One-to-one correspondence to triggers -> Triggers Abstraction Level

Instead to specify if written triggers in target generator/framework/library syntax has one-to-one corresprondence to triggers I would rather say if the generator/framework/library is abstracting the trigger away or not. (e.g. YATAPI -> One-to-one correspondence to triggers, LangUMS -> does abstract triggers partially, and so on)

- Death Counter Abstraction

Give the reader an insight whether the generator/compiler does abstract the death counter away. (e.g. YATAPI -> No, LangUMS -> yes, and so on)

- Triggers Integration Level

Perhaps it is considerable to add this and give the reader the insight how the generated/compiler triggers are integrated to maps (YATAPI -> Copy & Paste through SCMDraft, LangUMS -> .scx-Map Injection, and so on)

In my opinion the current comparison table is selfish and does not reflect the truth.

**Comment by sethmachine** [comment]
I'm happy to update the table to reflect the functionality of your project you think isn't accurately reflected in the table.  I wrote the code in this repo over 2 years ago and advertised it on staredit.net.  

I'll close the issue once I make an updated table to reflect your feedback.  

The intent behind the table is to draw some criticism to the mapping community, because overall the tools released have been poorly documented, aren't maintained any more, or written in a way that makes extending them difficult.  The fact that in 2019 I had to come up with a simple Python preprocessor rather than using any of the existing map making tools should say a lot.  Starcraft has been out for over 20 years; there should be much higher quality projects that treat map making like any other software development project.

**Comment by teneko** [comment]
You are right with your critism. Now I get a better picture.

I have got the thought too, that the programmer scene for StarCraft is very small and when a good program has been released it is not well presented or not adequate appreciated in form of web presence, documentation, source code and its documentation. Personally I think, that LangUMS is a good counterpart, used it as much as I could until I faced limitations, but that's another story. Your program is also very welcomed, but personally I do not like the idea to press a language (trigger language) in an existing language. Statements like `trigger.compile()` or the imports seems just not right, but these are only my two cents.

I will soon make a comprehensive comparison table, maybe you want take a look at it.

**Comment by teneko** [comment]
Here it is, the comparison table. It got quite extensive and took some time:
https://github.com/SCUMSLang/SCUMSLang#2-comparison-table

I know I drew critism at your comparison table, but honestly, I am not sure how it is best to update your comparison table. Take a look and decide yourself. :)
